/**
 * @file Tests that the stylelint gate actually gates.
 *
 * `tests/test_stylelint_gate.py` covers the wiring: it replaces `bun` with a
 * cmd-mox double and proves `make stylelint` calls `bun run lint:css` and
 * propagates a non-zero exit. That says nothing about the linter itself. With
 * the double in place the rules never run, so a `stylelint.config.js` that
 * had been loosened into silence — every rule off, or a `files` glob
 * matching nothing — would satisfy every assertion there.
 *
 * These tests close that half by running the real thing. A violation is
 * written into the tree stylelint is configured to scan, and the gate is
 * required to fail on it and to pass again once it is gone. That is the same
 * shape as `lint-gate.test.mjs`, and for the same reason: asserting the
 * configuration says what it says would only prove the file's contents, not
 * that stylelint agrees.
 *
 * The `make fmt` half is covered too, because `fmt` runs `stylelint --fix`
 * and the generators write blocks that the preset would otherwise reshape.
 * That coexistence rests on `--fix` leaving a disabled range alone, which is
 * asserted here rather than assumed. `fmt` itself is never run: it reformats
 * every Markdown file in the repository, so the wiring is read from
 * `make -n` and the fixing behaviour is exercised through `bun run
 * lint:css:fix` directly.
 *
 * Fixtures are removed in `afterEach` whether the assertion passed or not,
 * so nothing is left behind for the next run — or for `make all` — to trip
 * over. Like the other gate tests here, these need exclusive use of the
 * working tree; running two suites at once will make them fight over the
 * fixtures.
 */
import { afterEach, describe, expect, test } from "bun:test";
import { spawnSync } from "node:child_process";
import { existsSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const REPO_ROOT = join(dirname(fileURLToPath(import.meta.url)), "..", "..");

/* Inside `src/styles/`, which is the tree `lint:css` scans. A fixture outside
   it would pass by being unseen, which would prove nothing. */
const FIXTURE = join(REPO_ROOT, "src", "styles", "stylelint-gate-fixture.css");

/* Two violations the standard preset reports and `--fix` alone cannot excuse:
   a colour written in the legacy comma form, and a redundant longhand after
   its shorthand. Written otherwise-tidy so a failure is attributable to the
   rules rather than to stray whitespace. */
const VIOLATION = `.stylelint-gate-fixture {
  color: rgba(0, 0, 0, 0.5);
  overflow: hidden;
  overflow-y: hidden;
}
`;

/* CSS the preset accepts, used to prove the gate's verdict tracks the content
   rather than the mere presence of another file. */
const CLEAN = `.stylelint-gate-fixture {
  color: rgb(0 0 0 / 50%);
  overflow: hidden;
}
`;

/* A second fixture, for the `--fix` tests. Kept separate from FIXTURE so the
   two describe blocks cannot collide. */
const FMT_FIXTURE = join(REPO_ROOT, "src", "styles", "stylelint-fmt-fixture.css");

/* A fence around content the preset would otherwise reshape — one rule per
   line, legacy colour notation — with a fixable violation outside it. This is
   the shape the Pygments generators emit, and `--fix` must rewrite only the
   part outside the fence. */
const FENCED = `/* stylelint-disable -- Generated by a fixture; change the generator. */
.stylelint-fmt-fixture .a { color: rgba(0, 0, 0, 0.5); font-style: italic; }
.stylelint-fmt-fixture .b { color: rgba(0, 0, 0, 0.5); }
/* stylelint-enable */

.stylelint-fmt-fixture-outside {
  color: rgba(0, 0, 0, 0.5);
}
`;

/* Run a make target and report how it exited. MAKEFLAGS is cleared because
   the suite may itself run under a parent make. */
function make(target) {
  const result = spawnSync("make", [target], {
    cwd: REPO_ROOT,
    encoding: "utf8",
    env: { ...process.env, MAKEFLAGS: "" },
  });
  return { status: result.status, output: `${result.stdout ?? ""}${result.stderr ?? ""}` };
}

/* Run a package script and report how it exited. */
function bunRun(script) {
  const result = spawnSync("bun", ["run", script], {
    cwd: REPO_ROOT,
    encoding: "utf8",
    env: { ...process.env, MAKEFLAGS: "" },
  });
  return { status: result.status, output: `${result.stdout ?? ""}${result.stderr ?? ""}` };
}

afterEach(() => {
  rmSync(FIXTURE, { force: true });
  rmSync(FMT_FIXTURE, { force: true });
});

describe("the stylelint target", () => {
  test("passes on the tree as committed", () => {
    expect(existsSync(FIXTURE)).toBe(false);
    expect(make("stylelint").status).toBe(0);
  });

  test("fails on an introduced violation, and passes once it is removed", () => {
    expect(existsSync(FIXTURE)).toBe(false);

    writeFileSync(FIXTURE, VIOLATION);
    const dirty = make("stylelint");
    expect(dirty.status).not.toBe(0);
    expect(dirty.output).toContain("color-function-notation");
    expect(dirty.output).toContain("declaration-block-no-redundant-longhand-properties");

    rmSync(FIXTURE);
    expect(make("stylelint").status).toBe(0);
  });

  test("passes on a conforming file, so the verdict tracks content not presence", () => {
    writeFileSync(FIXTURE, CLEAN);
    expect(make("stylelint").status).toBe(0);
  });

  test("names the offending file, so a failure is actionable", () => {
    writeFileSync(FIXTURE, VIOLATION);
    expect(make("stylelint").output).toContain("stylelint-gate-fixture.css");
  });

  test("leaves no fixture behind", () => {
    expect(existsSync(FIXTURE)).toBe(false);
    const tracked = spawnSync("git", ["status", "--porcelain"], {
      cwd: REPO_ROOT,
      encoding: "utf8",
    });
    expect(tracked.stdout).not.toContain("stylelint-gate-fixture");
  });
});

describe("the fmt integration", () => {
  test("`make fmt` reaches the stylelint fixer", () => {
    /* Read from a dry run rather than executing: `fmt` also reformats every
       Markdown file in the repository, which no test should do. */
    const planned = spawnSync("make", ["-n", "fmt"], {
      cwd: REPO_ROOT,
      encoding: "utf8",
      env: { ...process.env, MAKEFLAGS: "" },
    });
    expect(planned.status).toBe(0);
    expect(planned.stdout).toContain("bun run lint:css:fix");
  });

  test("the fixer rewrites a fixable violation under src/", () => {
    writeFileSync(FMT_FIXTURE, ".stylelint-fmt-fixture {\n  color: rgba(0, 0, 0, 0.5);\n}\n");

    expect(bunRun("lint:css:fix").status).toBe(0);

    /* The legacy comma form is rewritten to the modern one, which is what
       proves stylelint ran with --fix over this tree rather than merely
       reporting. */
    expect(readFileSync(FMT_FIXTURE, "utf8")).toContain("rgb(0 0 0 / 50%)");
    expect(make("stylelint").status).toBe(0);
  });

  test("the fixer leaves a disabled range byte-identical", () => {
    writeFileSync(FMT_FIXTURE, FENCED);
    const fenceOf = (text) =>
      text.slice(text.indexOf("/* stylelint-disable"), text.indexOf("/* stylelint-enable */"));

    expect(bunRun("lint:css:fix").status).toBe(0);
    const fixed = readFileSync(FMT_FIXTURE, "utf8");

    /* The guarantee `make fmt` and the Pygments generators both depend on:
       without it the formatter would expand the generated one-rule-per-line
       output and the next generator run would collapse it again, with the
       staleness test failing on whichever ran last. */
    expect(fenceOf(fixed)).toBe(fenceOf(FENCED));

    /* And the fence is a fence, not a blanket: outside it, fixing still
       happens, so a passing assertion above cannot come from --fix being
       inert. */
    expect(fixed).toContain("color: rgb(0 0 0 / 50%);\n}");
  });
});
