"""Generate femtologging syntax CSS from its instrument palette.

Run ``uv run python scripts/generate_femtologging_pygments_css.py`` after
changing ``FemtoStyle``. The entire syntax partial is generated; semantic
panel layout remains in ``src/styles/femtologging/content.css``.
"""

from pathlib import Path

from pygments.formatters.html import HtmlFormatter

from df12_pages.femtologging_highlighting import FemtoStyle
from scripts.pygments_css import token_rules

TARGET = Path(__file__).resolve().parents[1] / "src/styles/femtologging/syntax.css"


def _build_css() -> str:
    """Build scoped token variables and rules from FemtoStyle."""
    variables, rules = token_rules(
        HtmlFormatter(style=FemtoStyle, cssclass="fl-syntax"),
        FemtoStyle,
        "fl-syntax",
        "--fl-syntax-",
        "600",
    )
    lines = [
        "/* Generated by scripts/generate_femtologging_pygments_css.py. */",
        "/* stylelint-disable -- Generated token rules; edit FemtoStyle. */",
        ":root {",
        *variables,
        "}",
        ".fl-syntax { background: var(--color-carbon); }",
        *rules,
        "/* stylelint-enable */",
        "",
    ]
    return "\n".join(lines)


if __name__ == "__main__":
    TARGET.write_text(_build_css(), encoding="utf-8")
