"""Regenerate the ``.cuprum-syntax`` Pygments rules in ``syntax.css``.

Reads the token colours from
:class:`df12_pages.cuprum_highlighting.CuprumStyle`, exposes each as a
``--cuprum-syntax-*`` CSS variable, and rewrites the marked block in
``src/static/cuprum/assets/styles/syntax.css``. The stylesheet path is
resolved relative to this script, so it may be run from any directory:

    uv run python scripts/generate_cuprum_pygments_css.py

This mirrors ``generate_stilyagi_pygments_css.py``: the generator owns only
the token block, and the layout rules above the marker stay handwritten. The
script is idempotent: rerunning it without changing the style leaves the
stylesheet untouched.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

from pygments.formatters.html import HtmlFormatter

from df12_pages.cuprum_highlighting import CuprumStyle
from scripts.pygments_css import token_rules

STYLESHEET = (
    Path(__file__).resolve().parent.parent
    / "src"
    / "static"
    / "cuprum"
    / "assets"
    / "styles"
    / "syntax.css"
)
BEGIN = (
    "/* BEGIN generated cuprum-pygments (scripts/generate_cuprum_pygments_css.py) */"
)
END = "/* END generated cuprum-pygments */"
#: Stylelint is switched off across the block: the token rules are emitted
#: one per line, and a finding inside the markers is a change to this
#: generator, not to the stylesheet.
STYLELINT_DISABLE = (
    "/* stylelint-disable -- Generated by scripts/generate_cuprum_pygments_css.py;"
    " change the generator, not this block. */"
)
STYLELINT_ENABLE = "/* stylelint-enable */"
CSS_CLASS = "cuprum-syntax"
VARIABLE_PREFIX = "--cuprum-syntax-"
#: IBM Plex Mono ships 400, 500, and 600 here; semibold is the heaviest cut.
BOLD_WEIGHT = "600"


def build_css() -> str:
    """Build the generated CSS block from the Cuprum style."""
    formatter = HtmlFormatter(style=CuprumStyle, cssclass=CSS_CLASS)
    variables, rules = token_rules(
        formatter,
        CuprumStyle,
        CSS_CLASS,
        VARIABLE_PREFIX,
        BOLD_WEIGHT,
    )

    lines = [
        BEGIN,
        STYLELINT_DISABLE,
        "",
        ":root {",
        *variables,
        "}",
        "",
        *rules,
        STYLELINT_ENABLE,
        "",
        END,
    ]
    return "\n".join(lines)


def main() -> int:
    """Rewrite the marked block in the stylesheet."""
    css = STYLESHEET.read_text(encoding="utf-8") if STYLESHEET.exists() else ""
    block = build_css()
    pattern = re.compile(re.escape(BEGIN) + r".*?" + re.escape(END), re.DOTALL)
    if pattern.search(css):
        updated = pattern.sub(lambda _match: block, css)
    else:
        updated = (css.rstrip("\n") + "\n\n" if css.strip() else "") + block + "\n"
    if updated != css:
        STYLESHEET.parent.mkdir(parents=True, exist_ok=True)
        STYLESHEET.write_text(updated, encoding="utf-8")
        sys.stdout.write("syntax.css updated\n")
    else:
        sys.stdout.write("syntax.css unchanged\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
